apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-http-echo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manifests/http-hello
    repoURL: https://github.com/slim-sandbox/argocd-demo.git
    targetRevision: HEAD
  kustomize:
      nameSuffix: -kustomized
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
